In [1]:
from gensim.models import Word2Vec
from gensim import models

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
model = models.KeyedVectors.load_word2vec_format('data/GoogleNews-vectors-negative300.bin', binary=True)

In [4]:
df = pd.read_csv('names.csv', header=None)
# col_names = pd.read_csv('names.csv', header=None).values.tolist()
tuples = [tuple(x) for x in df.values]
# tuples
col_names = list()
for t in tuples:
    for x in t:
#         print(x)
        col_names.append(x)

In [9]:
data = dict()
i = 0
for name in col_names:
    x = model[name]
    x=np.append(x,str(int(i%4)))#4topics
    x=np.append(x,name)
    data[i] = x
    i+=1

In [10]:
df = pd.DataFrame(data)

In [11]:
df = df.T
df.rename(columns={300: 'class', 301:'word'}, inplace=True)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,292,293,294,295,296,297,298,299,class,word
0,-0.18164062,0.16503906,-0.16601562,0.35742188,-0.092285156,0.20117188,-0.0546875,-0.26171875,-0.17285156,-0.080566406,...,-0.14941406,0.3984375,0.09277344,0.033935547,-0.061523438,0.15917969,0.12792969,0.0022277832,0,food
1,0.067871094,-0.041259766,0.100097656,0.05883789,0.05444336,0.017578125,0.072265625,-0.091308594,0.072265625,0.122558594,...,-0.15039062,0.17578125,0.10644531,0.15722656,-0.11328125,0.10449219,-0.08544922,-0.15429688,1,service
2,0.12109375,0.28125,0.10644531,0.025634766,-0.11230469,0.040527344,-0.0066223145,-0.17285156,-0.36328125,0.14257812,...,-0.064941406,0.07470703,0.11816406,0.18554688,0.24804688,-0.2734375,0.072753906,0.0134887695,2,ambience
3,0.079589844,0.018798828,0.109375,0.018676758,-0.11425781,0.12011719,0.17285156,-0.020629883,0.30664062,0.26757812,...,-0.16601562,-0.080078125,0.14453125,0.3984375,0.064453125,-0.06640625,0.07324219,-0.18847656,3,value
4,-0.026855469,0.08105469,-0.171875,0.22753906,-0.14160156,0.040527344,0.22949219,-0.22753906,-0.33203125,0.13183594,...,-0.17480469,-0.05517578,0.19726562,0.19921875,-0.36132812,0.10107422,0.14257812,0.28125,0,foodstuff

In [12]:
df.to_csv("./250google_vector.csv",index=False)